# Generated by Django 3.2.5 on 2021-08-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
