# Generated by Django 3.2.6 on 2021-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210812_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(to='products.Option'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
